<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE test-suite [
    <!ELEMENT test-suite (test-cases+)>
    <!ELEMENT test-cases (input-file,test-case+)>
    <!ELEMENT input-file (#PCDATA)>
    <!ELEMENT test-case (xpath,output)>
    <!ELEMENT xpath (#PCDATA)>
    <!ELEMENT output (#PCDATA)>

    <!ENTITY xalan-tests "resources/XSLT-testsuite-04/TESTS/Xalan_Conformance_Tests">
    <!ENTITY msft-tests "resources/XSLT-testsuite-04/TESTS/MSFT_Conformance_Tests">
]>
<test-suite>
    <test-cases>
        <input-file>&xalan-tests;/attribset/attribset20.xml</input-file>
        <test-case>
            <xpath>/docs/doc/*/@ped:att1</xpath>
            <output>a,c,</output>
        </test-case>
        <test-case>
            <xpath>/docs/doc/*/@xml:att1</xpath>
            <output>b,d,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes01.xml</input-file>
        <test-case>
            <xpath>name(/.//center/ancestor::*)</xpath>
            <output>near-north,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor::*[1])</xpath>
            <output>near-north,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor::*[2])</xpath>
            <output>north,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor::*[3])</xpath>
            <output>far-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes02.xml</input-file>
        <test-case>
            <xpath>name(/.//center/ancestor-or-self::*)</xpath>
            <output>center,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor-or-self::*[1])</xpath>
            <output>center,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor-or-self::*[2])</xpath>
            <output>near-north,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor-or-self::*[3])</xpath>
            <output>north,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/ancestor-or-self::*[4])</xpath>
            <output>far-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes03.xml</input-file>
        <test-case>
            <xpath>name(/.//center/attribute::*)</xpath>
            <output>center-attr-1,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/attribute::*[1])</xpath>
            <output>center-attr-1,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/attribute::*[2])</xpath>
            <output>center-attr-2,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/attribute::*[3])</xpath>
            <output>center-attr-3,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes04.xml</input-file>
        <test-case>
            <xpath>name(/.//center/child::*)</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/child::*[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/child::*[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/child::*[3])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes05.xml</input-file>
        <test-case>
            <xpath>name(/.//center/descendant::*)</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant::*[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant::*[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant::*[3])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant::*[4])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant::*[5])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes06.xml</input-file>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*)</xpath>
            <output>center,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*[1])</xpath>
            <output>center,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*[2])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*[3])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*[4])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*[5])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/descendant-or-self::*[6])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes07.xml</input-file>
        <test-case>
            <xpath>name(/.//center/following::*)</xpath>
            <output>near-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following::*[1])</xpath>
            <output>near-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following::*[2])</xpath>
            <output>east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following::*[3])</xpath>
            <output>far-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following::*[4])</xpath>
            <output>way-out-yonder-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following::*[5])</xpath>
            <output>out-yonder-east,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes08.xml</input-file>
        <test-case>
            <xpath>name(/.//center/preceding::*)</xpath>
            <output>near-west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding::*[1])</xpath>
            <output>near-west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding::*[2])</xpath>
            <output>west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding::*[3])</xpath>
            <output>far-west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding::*[4])</xpath>
            <output>out-yonder-west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding::*[5])</xpath>
            <output>way-out-yonder-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes09.xml</input-file>
        <test-case>
            <xpath>name(/.//center/following-sibling::*)</xpath>
            <output>near-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following-sibling::*[1])</xpath>
            <output>near-east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following-sibling::*[2])</xpath>
            <output>east,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/following-sibling::*[3])</xpath>
            <output>far-east,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes10.xml</input-file>
        <test-case>
            <xpath>name(/.//center/preceding-sibling::*)</xpath>
            <output>near-west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding-sibling::*[1])</xpath>
            <output>near-west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding-sibling::*[2])</xpath>
            <output>west,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/preceding-sibling::*[3])</xpath>
            <output>far-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes11.xml</input-file>
        <test-case>
            <xpath>name(/.//center/parent::*)</xpath>
            <output>near-north,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/parent::*[1])</xpath>
            <output>near-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes12.xml</input-file>
        <test-case>
            <xpath>name(/.//center/self::*)</xpath>
            <output>center,</output>
        </test-case>
        <test-case>
            <xpath>name(/.//center/self::*[1])</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes13.xml</input-file>
        <test-case>
            <xpath>string(//text()[ancestor::*[@new='true'][not(text())]][1])</xpath>
            <output>is new,</output>
        </test-case>
        <test-case>
            <xpath>string((//text()[ancestor::*[2][@new]])[1])</xpath>
            <output>is new,</output>
        </test-case>
        <test-case>
            <xpath>string((//text()[ancestor::*[2][@new]])[2])</xpath>
            <output>is new but has text,</output>
        </test-case>
        <test-case>
            <xpath>string((//text()[ancestor::*[2][@new]])[3])</xpath>
            <output>is not new,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes14.xml</input-file>
        <test-case>
            <xpath>//baz/ancestor-or-self::*[@att1][1]/@att1</xpath>
            <output>a,</output>
        </test-case>
        <test-case>
            <xpath>(//baz/ancestor-or-self::*)[@att1][1]/@att1</xpath>
            <output>c,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes16.xml</input-file>
        <test-case>
            <xpath>name(//center/ancestor::*[3])</xpath>
            <output>far-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes17.xml</input-file>
        <test-case>
            <xpath>name(//center/ancestor-or-self::*[1])</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes18.xml</input-file>
        <test-case>
            <xpath>name(//center/attribute::*[2])</xpath>
            <output>center-attr-2,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes19.xml</input-file>
        <test-case>
            <xpath>//center/@*</xpath>
            <output>c1,c2,c3,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes20.xml</input-file>
        <test-case>
            <xpath>name(//center/@*[2])</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes21.xml</input-file>
        <test-case>
            <xpath>name(//center/child::*[2])</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes22.xml</input-file>
        <test-case>
            <xpath>name(//center/child::near-south)</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/child::near-south-west)</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes23.xml</input-file>
        <test-case>
            <xpath>name(//center/descendant::*[3])</xpath>
            <output>far-south,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes24.xml</input-file>
        <test-case>
            <xpath>name(//center/descendant::far-south)</xpath>
            <output>far-south,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes25.xml</input-file>
        <test-case>
            <xpath>name(//center/descendant-or-self::*[3])</xpath>
            <output>south,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes26.xml</input-file>
        <test-case>
            <xpath>name(//center/descendant-or-self::far-south)</xpath>
            <output>far-south,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes27.xml</input-file>
        <test-case>
            <xpath>name(//center/descendant-or-self::center)</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes28.xml</input-file>
        <test-case>
            <xpath>name(//center/following::*[4])</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes29.xml</input-file>
        <test-case>
            <xpath>name(//center/following::out-yonder-east)</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes30.xml</input-file>
        <test-case>
            <xpath>name(//center/preceding::*[4])</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes31.xml</input-file>
        <test-case>
            <xpath>name(//center/preceding::out-yonder-west)</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes32.xml</input-file>
        <test-case>
            <xpath>name(//center/following-sibling::*[2])</xpath>
            <output>east,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes33.xml</input-file>
        <test-case>
            <xpath>name(//center/following-sibling::east)</xpath>
            <output>east,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes34.xml</input-file>
        <test-case>
            <xpath>name(//center/preceding-sibling::*[2])</xpath>
            <output>west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes35.xml</input-file>
        <test-case>
            <xpath>name(//center/preceding-sibling::west)</xpath>
            <output>west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes36.xml</input-file>
        <test-case>
            <xpath>name(//center/parent::near-north)</xpath>
            <output>near-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes37.xml</input-file>
        <test-case>
            <xpath>name(//center/parent::*[1])</xpath>
            <output>near-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes38.xml</input-file>
        <test-case>
            <xpath>name(//center/parent::foo)</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes39.xml</input-file>
        <test-case>
            <xpath>name(//center/..)</xpath>
            <output>near-north,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes40.xml</input-file>
        <test-case>
            <xpath>name(//center/self::center)</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes41.xml</input-file>
        <test-case>
            <xpath>name(//center/self::*[1])</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes42.xml</input-file>
        <test-case>
            <xpath>name(//center/self::foo)</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes43.xml</input-file>
        <test-case>
            <xpath>name(//center/.)</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes44.xml</input-file>
        <test-case>
            <xpath>name(//center/attribute::center-attr-2)</xpath>
            <output>center-attr-2,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes45.xml</input-file>
        <test-case>
            <xpath>name(//center/@center-attr-2)</xpath>
            <output>center-attr-2,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes46.xml</input-file>
        <test-case>
            <xpath>//center/../@width</xpath>
            <output>22,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes47.xml</input-file>
        <test-case>
            <xpath>/docs/doc/..//foo/@att1</xpath>
            <output>c,b,a,a,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes48.xml</input-file>
        <test-case>
            <xpath>name(//center/child::*/child::*)</xpath>
            <output>south,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes49.xml</input-file>
        <test-case>
            <xpath>name(//center/child::*/descendant::*)</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name((//center/child::*/descendant::*)[1])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name((//center/child::*/descendant::*)[2])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name((//center/child::*/descendant::*)[3])</xpath>
            <output>,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes50.xml</input-file>
        <test-case>
            <xpath>name((//center/descendant::*/child::*))</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name((//center/descendant::*/child::*)[1])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name((//center/descendant::*/child::*)[2])</xpath>
            <output>far-south,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes51.xml</input-file>
        <test-case>
            <xpath>name((//near-north/center//child::*))</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//child::*)[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//child::*)[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//child::*)[3])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//child::*)[4])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//child::*)[5])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes52.xml</input-file>
        <test-case>
            <xpath>name(//near-north/center//descendant::*)</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center//descendant::*[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center//descendant::*[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center//descendant::*[3])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center//descendant::*[4])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center//descendant::*[5])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes53.xml</input-file>
        <test-case>
            <xpath>name(//near-north/center/descendant::*)</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/descendant::*[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/descendant::*[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/descendant::*[3])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/descendant::*[4])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/descendant::*[5])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes54.xml</input-file>
        <test-case>
            <xpath>name(//near-north/center/child::*)</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/child::*[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/child::*[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name(//near-north/center/child::*[3])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes55.xml</input-file>
        <test-case>
            <xpath>name((//near-north/center//*))</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//*)[1])</xpath>
            <output>near-south-east,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//*)[2])</xpath>
            <output>near-south,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//*)[3])</xpath>
            <output>south,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//*)[4])</xpath>
            <output>far-south,</output>
        </test-case>
        <test-case>
            <xpath>name((//near-north/center//*)[5])</xpath>
            <output>near-south-west,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes56.xml</input-file>
        <test-case>
            <xpath>name((//doc//xx/descendant::*))</xpath>
            <output>xxchild,</output>
        </test-case>
        <test-case>
            <xpath>name((//doc//xx/descendant::*)[1])</xpath>
            <output>xxchild,</output>
        </test-case>
        <test-case>
            <xpath>name((//doc//xx/descendant::*)[2])</xpath>
            <output>xxchild,</output>
        </test-case>
        <test-case>
            <xpath>name((//doc//xx/descendant::*)[3])</xpath>
            <output>childofxx,</output>
        </test-case>
        <test-case>
            <xpath>name((//doc//xx/descendant::*)[4])</xpath>
            <output>xxsub,</output>
        </test-case>
        <test-case>
            <xpath>name((//doc//xx/descendant::*)[5])</xpath>
            <output>xxsubsub,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes57.xml</input-file>
        <test-case>
            <xpath>//doc//title</xpath>
            <output>Test for source tree depth,Level A,Level B,Level C,Level D,Level E,Level F,Level G,Level H,Level I,Level J,Level K,Level L,Level M,Level N,Level O,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes59.xml</input-file>
        <test-case>
            <xpath>//doc/namespace::*</xpath>
            <output>http://www.w3.org/XML/1998/namespace,http://somebody.elses.extension,http://xml.apache.org/xslt/java,http://tester.com,http://buster.com,http://administrator.com,http://www.w3.org/XML/1998/namespace,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes60.xml</input-file>
        <test-case>
            <xpath>//center/attribute::*</xpath>
            <output>c1,c2,c3,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes63.xml</input-file>
        <test-case>
            <xpath>name(//center/self::*[near-south])</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes64.xml</input-file>
        <test-case>
            <xpath>name(//center/self::*[@center-attr-2])</xpath>
            <output>center,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes65.xml</input-file>
        <test-case>
            <xpath>//center/self::text()</xpath>
            <output></output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes66.xml</input-file>
        <test-case>
            <xpath>//center/self::comment()</xpath>
            <output></output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes67.xml</input-file>
        <test-case>
            <xpath>//center/self::processing-instruction()</xpath>
            <output></output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes68.xml</input-file>
        <test-case>
            <xpath>//doc/namespace::*</xpath>
            <output>http://www.w3.org/XML/1998/namespace,http://somebody.elses.extension,</output>
        </test-case>
        <test-case>
            <xpath>//section/namespace::*</xpath>
            <output>http://www.w3.org/XML/1998/namespace,http://somebody.elses.extension,http://foo.com,</output>
        </test-case>
        <test-case>
            <xpath>//inner/namespace::*</xpath>
            <output>http://www.w3.org/XML/1998/namespace,http://somebody.elses.extension,http://foo.com,http://whiz.com/special/page,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes69.xml</input-file>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*)</xpath>
            <output>west,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*[1])</xpath>
            <output>west,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*[2])</xpath>
            <output>near-west,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*[3])</xpath>
            <output>center,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*[4])</xpath>
            <output>near-east,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*[5])</xpath>
            <output>east,</output>
        </test-case>
        <test-case>
            <xpath>name(//center/preceding-sibling::*/following-sibling::*[6])</xpath>
            <output>far-east,</output>
        </test-case>
    </test-cases>
    <test-cases>
        <input-file>&xalan-tests;/axes/axes71.xml</input-file>
        <test-case>
            <xpath>name(//center/preceding-sibling::*[2]/following-sibling::*)</xpath>
            <output>near-west,</output>
        </test-case>